version: '3.7'
services:
  redis:
    image: redis:alpine
    container_name: ${APP_NAME}_redis
  #ubuntu:
   # image: library/ubuntu:22.10
    #container_name: ${APP_NAME}_ubuntu

  postgres:
    image: library/postgres:latest
    container_name: ${APP_NAME}_postgres
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 8080:8080

  nginx:
    image: library/nginx:latest
    container_name: ${APP_NAME}_nginx
    ports:
      # For access server at localhost:${WEB_SERVER_PORT}
      - ${WEB_SERVER_PORT}:80
    volumes:
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './src:/var/www/html'

  php:
    image: library/php:fpm
    build: ./docker/php
    container_name: ${APP_NAME}_php
    ports:
      - 9000:9000
    volumes:
      - './src:/var/www/html'
